services:
  - type: web
    name: pendencias-manager-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /v3/api-docs
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: pendencias-manager-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: pendencias-manager-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: pendencias-manager-db
          property: password
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.postgresql.Driver
      - key: SPRING_JPA_DATABASE_PLATFORM
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_H2_CONSOLE_ENABLED
        value: "false"
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 3600000

databases:
  - name: pendencias-manager-db
    plan: free
